In [4]:
import numpy as np

In [5]:
a = np.array( [[1,2,3],[4,5,6],[7,8,9]])
type(a)

numpy.ndarray

In [13]:
a = np.array( [[1,2,3],[4,5,6],[7,8,9]])
b = [[1,2,3],[4,5,6],[7,8,9]]

a[0]
display(a[0])
print(a[0])
b[0]

array([1, 2, 3])

[1 2 3]


[1, 2, 3]

In [17]:
np.zeros(6)
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.empty(3, order='F')

array([ 9.75394660e+199,  1.30903169e-311, -0.00000000e+000])

In [30]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [43]:
cth = np.arange(5,20,2)
cth

np.append(cth,[1,2,3])


array([ 5,  7,  9, 11, 13, 15, 17, 19,  1,  2,  3])

In [41]:
np.delete(cth,0)


array([ 7,  9, 11, 13, 15, 17, 19])

In [45]:
contoh = [ 5,  7,  9, 11, 13, 15, 17, 19,  1,  2,  3]
np.sort(contoh)


array([ 1,  2,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [63]:
array_example = np.array(
    [[[0,1,2,3],[4,5,6,7]],
        [[0,1,2,3],[4,5,6,7]],
        [[0,1,2,3],[4,5,6,7]]])

array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [64]:
array_example.ndim


3

In [65]:
array_example.size

24

In [66]:
array_example.shape

(3, 2, 4)

In [70]:
array_example.reshape(4,3,2)

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[6, 7],
        [0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7],
        [0, 1]],

       [[2, 3],
        [4, 5],
        [6, 7]]])

In [68]:
example = np.array([[0,1,2,3],[4,5,6,7]])
example

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
example.ndim

2

In [59]:
example.size

8

In [60]:
example.shape

(2, 4)

In [61]:
example.reshape(4, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [72]:
a = np.array([0,1,2,3,4,5,7,8,9,10,11,12,13,14,15])
a

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [79]:
a2 = a[np.newaxis]
display(a2)
a3=a2[np.newaxis]
display(a3)
a3.shape

row_vector = a[:, np.newaxis]
display(row_vector.shape)
display(row_vector)

array([[ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

array([[[ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

(15, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [87]:
b = np.arange(5)
display(a)
display(a.shape)

c = np.expand_dims(b,axis=1)
display(c)
display(c.shape)

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15])

(15,)

array([[0],
       [1],
       [2],
       [3],
       [4]])

(5, 1)

In [85]:
example

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [88]:
example[example >=2]

array([2, 3, 4, 5, 6, 7])

In [89]:
limaPlus = (example >=5)
example[limaPlus]

array([5, 6, 7])

In [95]:
genap = (example %2 == 0)
example[genap]

example[example %2==0]

array([0, 2, 4, 6])

In [97]:
example[(example %2==0) & (example >3)] 

array([4, 6])

In [98]:
example[(example %2==0) | (example >=5)] 

array([0, 2, 4, 5, 6, 7])

In [101]:
a = np.arange(1,11)
b= a[3:8]
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
b

array([4, 5, 6, 7, 8])

In [105]:
a1= np.array([[0,1],[4,5]])
a2 = np.array([[2,3],[6,7]])

np.vstack((a1,a2))

array([[0, 1],
       [4, 5],
       [2, 3],
       [6, 7]])

In [106]:
np.hstack((a1,a2))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [108]:
display(a)
a2 = a[np.newaxis]
a4 = np.vstack((a1,a2))

a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 10

In [156]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [113]:
a = np.arange(3)
b = np.arange(4,7)

print(a)
print(b)

print (a+b)
print (a-b)
print (a*b)
print (a/b)

[0 1 2]
[4 5 6]
[4 6 8]
[-4 -4 -4]
[ 0  5 12]
[0.         0.2        0.33333333]


In [114]:
b.sum()

15

In [116]:
example

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [117]:
c.sum()

10

In [123]:
a2
a2.sum()

55

In [121]:
a3

array([[[ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [122]:
a3.sum()

114

In [129]:
c = ([[1,2,3,4],
      [5,6,7,8],
      [9,10,11,12]])
c

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [130]:
print(c.sum(axis = 0))

AttributeError: 'list' object has no attribute 'sum'

In [134]:
a *1.6

array([0. , 1.6, 3.2])

In [136]:
z = np.array([1,2,5])
z *15

array([15, 30, 75])

In [147]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [148]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [153]:
print(c.min())
print(c.max())
print(c.sum())
print(c.std())
print(c.min(axis = 1))
print(c.max(axis = 0))

1
12
78
3.452052529534663
[1 5 9]
[ 9 10 11 12]


In [162]:
z = np.zeros((6,2))
q = np.ones((6,2))
r = np.random.random((6,2))

print(z)
print(q)
print(r)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[8.08602576e-01 3.89648405e-01]
 [3.48785339e-01 9.76256060e-01]
 [3.50917081e-01 4.16151527e-04]
 [4.94766166e-02 7.19752810e-01]
 [9.87139236e-01 4.30549704e-01]
 [9.32074411e-01 6.08335289e-01]]


In [167]:
q + r

array([[1.80860258, 1.38964841],
       [1.34878534, 1.97625606],
       [1.35091708, 1.00041615],
       [1.04947662, 1.71975281],
       [1.98713924, 1.4305497 ],
       [1.93207441, 1.60833529]])

In [172]:
a1 = np.array([[0, 1],[4 ,5],[7,8]])
print (a1)
a2 = np.array([[0,1,2],[4,5,6],[8,9,10]])
print(a2)

[[0 1]
 [4 5]
 [7 8]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [174]:
np.dot(a2,a1)

array([[ 18,  21],
       [ 62,  77],
       [106, 133]])

In [181]:
a1 = np.array([[1,2],[3, 4],[5,6]])
print(a1)
print(a1[0])
print(a1[2])
print(a1[0:2])
print(a1[0,1])
print(a1[0][1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[5 6]
[[1 2]
 [3 4]]
2
2


In [184]:
display(a1)
print(a1.shape)
print(a1.T)
display(a1.T)

array([[1, 2],
       [3, 4],
       [5, 6]])

(3, 2)
[[1 3 5]
 [2 4 6]]


array([[1, 3, 5],
       [2, 4, 6]])

In [187]:
a= np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [191]:
a2 = a[np.newaxis]
a2.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [200]:
a3 = a2.reshape(-1,3)
a3

array([[0, 1, 2],
       [3, 4, 5]])

In [207]:
a4 = a3.flatten()
print(a4)
print (np.delete(a4,1))
print(a3)

[0 1 2 3 4 5]
[0 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [208]:
a4 = a3.ravel()
print(a4)
print (np.delete(a4,1))
print(a3)

[0 1 2 3 4 5]
[0 2 3 4 5]
[[0 1 2]
 [3 4 5]]
